apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      run: eureka
  template:
    metadata:
      labels:
        run: eureka
    spec:
      containers:
      - image: parks4754/eureka-server
        name: eureka
        ports:
        - containerPort: 80
